/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bintang.kasir.components;

import javax.swing.ImageIcon;

/**
 *
 * @author ACER
 */
public class MenuItemPanel extends javax.swing.JPanel {

    private int id, price, stock;
    private String name, imagePath;

    public interface MenuClickListener {
        void onMenuClicked(int id, String name, int price, int stock, String image);
    }
    private MenuClickListener listener;

    public void setMenuClickListener(MenuClickListener listener) {
        this.listener = listener;
    }
    
    public MenuItemPanel(int id, String name, int price, String imagePath, int stock) {
        this.id = id;
        this.name = name;
        this.price = price;
        this.imagePath = imagePath;
        this.stock = stock;
        
        initComponents();
        
        this.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (listener != null) {
                    listener.onMenuClicked(id, name, price, stock, imagePath);
                }
            }
        });
        
        menuName.setText(name);
        menuPrice.setText("Rp. " + price);
        menuImg.setIcon(new ImageIcon(getClass().getResource(imagePath)));
    }

    public int getId() {
        return id;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ItemPanel = new com.bintang.kasir.components.CustomPanel();
        jSeparator1 = new javax.swing.JSeparator();
        menuImg = new javax.swing.JLabel();
        menuName = new javax.swing.JLabel();
        menuPrice = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 246, 250));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setPreferredSize(new java.awt.Dimension(110, 120));
        setLayout(new java.awt.BorderLayout());

        ItemPanel.setBackground(new java.awt.Color(255, 255, 255));
        ItemPanel.setPreferredSize(new java.awt.Dimension(0, 0));
        ItemPanel.setRoundBottomLeft(20);
        ItemPanel.setRoundBottomRight(20);
        ItemPanel.setRoundTopLeft(20);
        ItemPanel.setRoundTopRight(20);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setPreferredSize(new java.awt.Dimension(100, 10));
        ItemPanel.add(jSeparator1);

        menuImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/coffee.png"))); // NOI18N
        menuImg.setPreferredSize(new java.awt.Dimension(100, 50));
        ItemPanel.add(menuImg);

        menuName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuName.setForeground(new java.awt.Color(31, 41, 55));
        menuName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuName.setText("Es Coklat Jawa");
        menuName.setPreferredSize(new java.awt.Dimension(110, 16));
        ItemPanel.add(menuName);

        menuPrice.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        menuPrice.setForeground(new java.awt.Color(107, 114, 128));
        menuPrice.setText("Rp20.000");
        ItemPanel.add(menuPrice);

        add(ItemPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.bintang.kasir.components.CustomPanel ItemPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel menuImg;
    private javax.swing.JLabel menuName;
    private javax.swing.JLabel menuPrice;
    // End of variables declaration//GEN-END:variables
}
