/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bintang.kasir.components;

import com.bintang.kasir.model.CartItem;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author ACER
 */
public class OrderItemPanel extends javax.swing.JPanel {

    public interface CartActionListener {
        void onQtyChanged(int id, int newQty);
        void onDelete(int id);
    }

    private CartItem itemData;
    private CartActionListener listener;
    
    public OrderItemPanel(CartItem item, CartActionListener listener) {
        this.itemData = item;
        this.listener = listener;
        initComponents();
        
        // Set text UI kamu (sesuaikan nama variabel JLabel kamu)
        menuName.setText(item.name);
        menuPrice.setText("Rp " + item.price);
        amountTxt.setText(String.valueOf(item.qty));
        
        // --- TAMBAHKAN LOGIKA SET GAMBAR DI SINI ---
        try {
            // Ambil gambar dari resources (folder assets)
            java.net.URL imgURL = getClass().getResource(item.image);
            if (imgURL != null) {
                ImageIcon icon = new ImageIcon(imgURL);
                // Kita kecilkan gambarnya (Misal: 60x60 pixel) agar rapi di keranjang
                Image img = icon.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH);
                menuImg.setIcon(new ImageIcon(img));
                menuImg.setText(""); // Hapus teks label jika ada
            } else {
                // Jika gambar tidak ditemukan di resources, coba ambil dari local path
                String projectPath = System.getProperty("user.dir");
                ImageIcon icon = new ImageIcon(projectPath + "/src/main/resources" + item.image);
                Image img = icon.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH);
                menuImg.setIcon(new ImageIcon(img));
                menuImg.setText("");
            }
        } catch (Exception e) {
            System.err.println("Gagal memuat gambar keranjang: " + e.getMessage());
        }

        // ACTION UNTUK TOMBOL MINUS (-)
        minusBtn.addActionListener(e -> {
            if (itemData.qty > 1) {
                itemData.qty--;
                amountTxt.setText(String.valueOf(itemData.qty));
                listener.onQtyChanged(itemData.id, itemData.qty);
            }
        });

        // ACTION UNTUK TOMBOL PLUS (+)
        plusBtn.addActionListener(e -> {
            if (itemData.qty < itemData.maxStock) {
                itemData.qty++;
                amountTxt.setText(String.valueOf(itemData.qty));
                listener.onQtyChanged(itemData.id, itemData.qty);
            } else {
                java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
                javax.swing.JOptionPane.showMessageDialog(parentWindow, "Stok maksimal hanya " + itemData.maxStock);
            }
        });

        // ACTION UNTUK TOMBOL DELETE
        deleteBtn.addActionListener(e -> {
            listener.onDelete(itemData.id);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customPanel1 = new com.bintang.kasir.components.CustomPanel();
        customPanel2 = new com.bintang.kasir.components.CustomPanel();
        right = new com.bintang.kasir.components.CustomPanel();
        customPanel3 = new com.bintang.kasir.components.CustomPanel();
        minusBtn = new javax.swing.JButton();
        plusBtn = new javax.swing.JButton();
        amountTxt = new javax.swing.JLabel();
        left = new javax.swing.JPanel();
        menuImg = new javax.swing.JLabel();
        center = new javax.swing.JPanel();
        menuName = new javax.swing.JLabel();
        menuPrice = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(250, 250, 250));
        setForeground(new java.awt.Color(250, 250, 250));

        customPanel1.setBackground(new java.awt.Color(255, 122, 40));
        customPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 0, 2, 2));
        customPanel1.setPreferredSize(new java.awt.Dimension(290, 80));
        customPanel1.setRoundBottomLeft(20);
        customPanel1.setRoundBottomRight(20);
        customPanel1.setRoundTopLeft(20);
        customPanel1.setRoundTopRight(20);
        customPanel1.setLayout(new java.awt.BorderLayout());

        customPanel2.setBackground(new java.awt.Color(250, 250, 250));
        customPanel2.setPreferredSize(new java.awt.Dimension(276, 76));
        customPanel2.setRoundBottomRight(20);
        customPanel2.setRoundTopRight(20);
        customPanel2.setLayout(new java.awt.BorderLayout());

        right.setBackground(new java.awt.Color(250, 250, 250));
        right.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 0, 20, 5));
        right.setPreferredSize(new java.awt.Dimension(90, 0));
        right.setRoundBottomRight(20);
        right.setRoundTopRight(20);
        right.setLayout(new java.awt.BorderLayout());

        customPanel3.setBackground(new java.awt.Color(255, 122, 40));
        customPanel3.setRoundBottomLeft(20);
        customPanel3.setRoundBottomRight(20);
        customPanel3.setRoundTopLeft(20);
        customPanel3.setRoundTopRight(20);
        customPanel3.setLayout(new java.awt.BorderLayout());

        minusBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        minusBtn.setForeground(new java.awt.Color(255, 255, 255));
        minusBtn.setText("-");
        minusBtn.setBorder(null);
        minusBtn.setBorderPainted(false);
        minusBtn.setContentAreaFilled(false);
        minusBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minusBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        minusBtn.setPreferredSize(new java.awt.Dimension(25, 23));
        customPanel3.add(minusBtn, java.awt.BorderLayout.WEST);

        plusBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        plusBtn.setForeground(new java.awt.Color(255, 255, 255));
        plusBtn.setText("+");
        plusBtn.setBorder(null);
        plusBtn.setBorderPainted(false);
        plusBtn.setContentAreaFilled(false);
        plusBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plusBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        plusBtn.setPreferredSize(new java.awt.Dimension(25, 23));
        customPanel3.add(plusBtn, java.awt.BorderLayout.EAST);

        amountTxt.setBackground(new java.awt.Color(255, 255, 255));
        amountTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        amountTxt.setForeground(new java.awt.Color(255, 255, 255));
        amountTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amountTxt.setText("10");
        customPanel3.add(amountTxt, java.awt.BorderLayout.CENTER);

        right.add(customPanel3, java.awt.BorderLayout.CENTER);

        customPanel2.add(right, java.awt.BorderLayout.EAST);

        left.setBackground(new java.awt.Color(250, 250, 250));
        left.setPreferredSize(new java.awt.Dimension(60, 0));
        left.setLayout(new java.awt.BorderLayout());

        menuImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/coffee.png"))); // NOI18N
        menuImg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        left.add(menuImg, java.awt.BorderLayout.CENTER);

        customPanel2.add(left, java.awt.BorderLayout.WEST);

        center.setBackground(new java.awt.Color(250, 250, 250));
        center.setPreferredSize(new java.awt.Dimension(128, 0));

        menuName.setBackground(new java.awt.Color(31, 41, 55));
        menuName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuName.setForeground(new java.awt.Color(31, 41, 55));
        menuName.setText("Es Coklat Jawa");

        menuPrice.setForeground(new java.awt.Color(107, 114, 128));
        menuPrice.setText("Rp10.000");

        javax.swing.GroupLayout centerLayout = new javax.swing.GroupLayout(center);
        center.setLayout(centerLayout);
        centerLayout.setHorizontalGroup(
            centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
            .addComponent(menuPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        centerLayout.setVerticalGroup(
            centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(menuName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuPrice)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        customPanel2.add(center, java.awt.BorderLayout.CENTER);

        customPanel1.add(customPanel2, java.awt.BorderLayout.EAST);

        deleteBtn.setToolTipText("");
        deleteBtn.setBorder(null);
        deleteBtn.setBorderPainted(false);
        deleteBtn.setContentAreaFilled(false);
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteBtn.addActionListener(this::deleteBtnActionPerformed);
        customPanel1.add(deleteBtn, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(customPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        
    }//GEN-LAST:event_deleteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountTxt;
    private javax.swing.JPanel center;
    private com.bintang.kasir.components.CustomPanel customPanel1;
    private com.bintang.kasir.components.CustomPanel customPanel2;
    private com.bintang.kasir.components.CustomPanel customPanel3;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JPanel left;
    private javax.swing.JLabel menuImg;
    private javax.swing.JLabel menuName;
    private javax.swing.JLabel menuPrice;
    private javax.swing.JButton minusBtn;
    private javax.swing.JButton plusBtn;
    private com.bintang.kasir.components.CustomPanel right;
    // End of variables declaration//GEN-END:variables
}
