/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bintang.kasir.components;

import com.bintang.kasir.ui.LoginForm;
import java.awt.Window;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author ACER
 */
public class SidebarPanel extends javax.swing.JPanel {

    public interface SidebarListener {
        void onCategorySelected(String category);
        void onDashboardSelected();
    }

    // 2. Buat variabel untuk menyimpan listener
    private SidebarListener listener;

    // 3. Buat method untuk mendaftarkan listener dari luar
    public void setSidebarListener(SidebarListener listener) {
        this.listener = listener;
    }
    
    public SidebarPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dashboardBtn = new javax.swing.JButton();
        makananBtn = new javax.swing.JButton();
        minumanBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 231, 235), 1, true));
        setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 1));
        jPanel1.setPreferredSize(new java.awt.Dimension(220, 0));

        jLabel1.setBackground(new java.awt.Color(31, 41, 55));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/hamburger-icon.png"))); // NOI18N
        jLabel1.setText("Sidebar Menu");

        dashboardBtn.setBackground(new java.awt.Color(102, 102, 102));
        dashboardBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dashboardBtn.setForeground(new java.awt.Color(107, 114, 128));
        dashboardBtn.setText("Dashboard");
        dashboardBtn.setBorder(null);
        dashboardBtn.setBorderPainted(false);
        dashboardBtn.setContentAreaFilled(false);
        dashboardBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardBtn.setFocusPainted(false);
        dashboardBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dashboardBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        dashboardBtn.addActionListener(this::dashboardBtnActionPerformed);

        makananBtn.setBackground(new java.awt.Color(102, 102, 102));
        makananBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        makananBtn.setForeground(new java.awt.Color(107, 114, 128));
        makananBtn.setText("Makanan");
        makananBtn.setBorder(null);
        makananBtn.setBorderPainted(false);
        makananBtn.setContentAreaFilled(false);
        makananBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        makananBtn.setFocusPainted(false);
        makananBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        makananBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        makananBtn.addActionListener(this::makananBtnActionPerformed);

        minumanBtn.setBackground(new java.awt.Color(102, 102, 102));
        minumanBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        minumanBtn.setForeground(new java.awt.Color(107, 114, 128));
        minumanBtn.setText("Minuman");
        minumanBtn.setBorder(null);
        minumanBtn.setBorderPainted(false);
        minumanBtn.setContentAreaFilled(false);
        minumanBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minumanBtn.setFocusPainted(false);
        minumanBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        minumanBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        minumanBtn.addActionListener(this::minumanBtnActionPerformed);

        logoutBtn.setBackground(new java.awt.Color(102, 102, 102));
        logoutBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(107, 114, 128));
        logoutBtn.setText("Logout");
        logoutBtn.setBorder(null);
        logoutBtn.setBorderPainted(false);
        logoutBtn.setContentAreaFilled(false);
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.setFocusPainted(false);
        logoutBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logoutBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        logoutBtn.addActionListener(this::logoutBtnActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dashboardBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(makananBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minumanBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(makananBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minumanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 442, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        Window window = SwingUtilities.getWindowAncestor(this);

        int confirm = JOptionPane.showConfirmDialog(
            window,
            "Apakah kamu yakin ingin logout?",
            "Logout",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            new LoginForm().setVisible(true);
            window.dispose();
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void makananBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makananBtnActionPerformed
        if (listener != null) {
            listener.onCategorySelected("makanan");
        }
    }//GEN-LAST:event_makananBtnActionPerformed

    private void minumanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minumanBtnActionPerformed
        if (listener != null) {
            listener.onCategorySelected("minuman");
        }
    }//GEN-LAST:event_minumanBtnActionPerformed

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        if (listener != null) {
            listener.onDashboardSelected();
        }
    }//GEN-LAST:event_dashboardBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton makananBtn;
    private javax.swing.JButton minumanBtn;
    // End of variables declaration//GEN-END:variables
}
